version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://musicaneon_owner:npg_rXmsKn3t4jbR@ep-winter-violet-a5z1fqov-pooler.us-east-2.aws.neon.tech/musicaneon?sslmode=require
