"""Added profile_picture to User

Revision ID: 0a22bd751215
Revises: 345d99d329d7
Create Date: 2025-03-26 23:26:36.507335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a22bd751215'
down_revision = '345d99d329d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=256), nullable=True))
        batch_op.alter_column('album',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.alter_column('album',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
