"""Added album and duration to Playlist

Revision ID: 345d99d329d7
Revises: 2d9e7aaf5f0f
Create Date: 2025-03-20 00:45:43.629789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345d99d329d7'
down_revision = '2d9e7aaf5f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('preview',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.alter_column('preview',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('duration')
        batch_op.drop_column('album')

    # ### end Alembic commands ###
